const data = {
    products:[
        {
            _id: '1',
            name: 'Midnight Blue Orchids',
            slug: 'midnight-blue-orchid',
            price: 850,
            category: 'Orchids',
            image: '/images/midnight-orchid.png',
            countInStock: 10,
            rating: 5,
            numReviews: 25,
            description: 'The most highly coveted of ornamental plants the delicate, exotic and graceful orchid represents love, luxury, beauty and strength. Mesmerize your loved ones with this luxurious orchid bouquet with Asparagus Fillers.',
            productDetails: [
                '6 Blue Orchids',
                'Green Delhi Asparagus Fillers',
                'Sky Blue Non Woven Paper Wrapping',
                'Beautifully Tied With White Ribbon'
            ],
        },
        {
            _id: '2',
            name: 'Soothing White Carnations',
            slug: 'soothing-white-carnations',
            price: 850,
            category: 'Carnations',
            image: '/images/white-carnations.png',
            countInStock: 10,
            rating: 4.5,
            numReviews: 10,
            description: "The pure, facinationg and royal God's Flower represents devotion, love and fascination. Enchant your other half with this calming carnations bouquet with Green Goldenrod Fillers.",
            productDetails: [
                '8 White Carnations',
                'Green Goldenrod Fillers',
                'Wrapped in White Paper',
                'Tied with White Ribbon',
            ],
        },
        {
            _id: '3',
            name: 'Timeless Red Roses',
            slug: 'timeless-red-roses',
            price: 750,
            category: 'Roses',
            image: '/images/red-roses.png',
            countInStock: 50,
            rating: 5,
            numReviews: 45,
            description: 'The classic beauty of flowers the romantic and passionate rose represents love, hope, gratitude, passion and compassion. Bring your loved ones this classic red rose bouquet with White Gypsy Flower Fillers, to show your love.',
            productDetails: [
                '10 Red Roses',
                'White Gypsy Flower Fillers',
                'Beautifully Wrapped with Non-woven Red Paper',
                'FNP Brown Strip Paper Packing',
                'Tied with Black Satin Ribbon',
            ],
        },
        {
            _id: '4',
            name: 'Heavenly White Roses',
            slug: 'attractive-asiatic-lilies',
            price: 650,
            category: 'Lilies',
            image: '/images/white-roses.png',
            countInStock: 20,
            rating: 4,
            numReviews: 15,
            description: 'The heavenly and divine white roses symbolizing loyalty, purity, and innocence make everyones day brighter just like its colours',
            productDetails: [
                '6 White Roses',
                'White Packing Paper',
                'White Color Ribbion',
                'Green Color Murraya Leaf Filler',
            ],
        },
        {
            _id: '5',
            name: 'Attractive Mixed Asiatic Lilies',
            slug: 'attractive-asiatic-lilies',
            price: 1350,
            category: 'Lilies',
            image: '/images/asiatic-lilies.png',
            countInStock: 20,
            rating: 4.5,
            numReviews: 37,
            description: 'Lilies have long been associated with love, devotion and purity. Charm everyone with this sweet and innocent beauty of the flower has ensured it remains tied to the ideas of fresh new life and rebirth.',
            productDetails: [
                '2 Pink Asiatic Lilies',
                '2 White Asiatic Lilies',
                '2 Orange Asiatic Lilies',
                'Green Color Goldenrod Fillers',
                'Packed in Pink and White Paper',
                'Tied with Green Raffia',
            ],
        },
    ]
}

export default data;